application: isthisstockgood
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: numpy
  version: "1.6.1"

handlers:
- url: /css
  static_dir: css
- url: /img
  static_dir: img
- url: /js
  static_dir: js
- url: /.*
  script: app.Controller.application
  secure: always
